import type { Metadata } from 'next'
import { Geist, Geist_Mono, Inter } from 'next/font/google'
import './globals.css'
import Header from './ui/Header'
import { cn } from '@/lib/utils'

const inter = Inter({subsets:['latin'],variable:'--font-sans'})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={cn('font-sans', "font-sans", inter.variable)}>
      <body className={cn('min-h-screen bg-background font-sans text-foreground antialiased', geistMono.variable)}>
        <Header />
        {children}
      </body>
    </html>
  )
}
